package fastAndSlowPointers.happyNumber

import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

// Test cases generated by ChatGPT
class SolutionTest {

    @Test
    fun testHappyNumber() {
        val solution = Solution()
        assertTrue(solution.isHappy(19))
        assertTrue(solution.isHappy(1))
        assertTrue(solution.isHappy(7))
    }

    @Test
    fun testNotHappyNumber() {
        val solution = Solution()
        assertFalse(solution.isHappy(2))
        assertFalse(solution.isHappy(4))
        assertFalse(solution.isHappy(16))
    }

    @Test
    fun testLargeInput() {
        val solution = Solution()
        assertFalse(solution.isHappy(999_999_999))
    }

    @Test
    fun testZero() {
        val solution = Solution()
        assertFalse(solution.isHappy(0))
    }
}
